### ISSUE TITLE
cant install using npm

### ISSUE THREAD

**Issue by zacsneds** [NastuzziSamy/vue-drag-resize-and-rotate#1]
Hey Samy.

I like the look of what you've done, except i can't install it.
After running 'npm i -s VueDragResizeAndRotate-and-rotate' I get nothing.
Is this the right command for this package?

Cheeers
Zac

**Comment by NastuzziSamy** [comment]
Hey ! 

My mistake, i did a bad replacement. 

It's actually `npm i -S vue-drag-resize-and-rotate` 

Do not hesitate to ask for anything
